{% set name = "libcufft" %}
{% set version = "12.1.0.78" %}
{% set cuda_version = "13.1" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 336732ded69b9f7f5cdca3e7e942732f1446933f2dccaf563c84b5caf058ad75  # [linux64]
  sha256: 66302c6927af275515c5bd68275250f7c6e47521938c4d77318c7cba1f8715c6  # [aarch64]
  sha256: b0a3df65c6ce60dc1aa695f47159a26d5172ac7411045abaeea2fbe948a42746  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0                      # [linux]

outputs:
  - name: libcufft
    files:
      - lib/libcufft*.so.*                            # [linux]
      - targets/{{ target_name }}/lib/libcufft*.so.*  # [linux]
      - Library\bin\cufft*64_*.dll                    # [win]
    build:
      binary_relocation: false
      # Repacked binaries on linux aarch64 have flag DT_TLSDESC (GNU_HASH),
      # which is not supported by LIEF and can raise ValueError during
      # overlinking checks. Ignore all cuFFT shared objects for overlinking checks.
      overlinking_ignore_patterns:  # [linux and aarch64]
        - "targets/{{ target_name }}/lib/libcufft*.so*"   # [linux and aarch64]
        - "targets/{{ target_name }}/lib/libcufftw*.so*"  # [linux and aarch64]
        - "lib/libcufft*.so*"                              # [linux and aarch64]
        - "lib/libcufftw*.so*"                             # [linux and aarch64]
      # conda_build.exceptions.RunPathError: runpaths check failed
      # ERROR (libcufft-dev,targets/*/lib/stubs/libcufft.so): runpaths ['$ORIGIN'] found
      # The stub files use $ORIGIN runpaths which are valid but flagged by conda-build
      # This whitelist allows $ORIGIN runpaths in the stub files during build-time validation.
      # Note: We have comprehensive rpath validation in test-rpath.sh that ensures all libraries
      # have the correct $ORIGIN rpath for runtime compatibility.
      runpath_whitelist:  # [linux]
        - $ORIGIN  # [linux]
      missing_dso_whitelist:
        # Needed for rpath issues with conda-build and use of --error-overlinking command-line argument
        - '$RPATH/libgcc_s.so.1'  # [linux]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libcufft.so.{{ version.split(".")[0] }}                             # [linux]
        - test -L $PREFIX/lib/libcufftw.so.{{ version.split(".")[0] }}                            # [linux]
        - test -L $PREFIX/lib/libcufft.so.{{ version }}                                           # [linux]
        - test -L $PREFIX/lib/libcufftw.so.{{ version }}                                          # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufft.so.{{ version.split(".")[0] }}   # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufftw.so.{{ version.split(".")[0] }}  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufft.so.{{ version }}                 # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufftw.so.{{ version }}                # [linux]
        - bash test-rpath.sh                                                                      # [linux]
        - if not exist %LIBRARY_BIN%\cufft64_{{ version.split(".")[0] }}.dll exit 1               # [win]
        - if not exist %LIBRARY_BIN%\cufftw64_{{ version.split(".")[0] }}.dll exit 1              # [win]
    about:
      home: https://developer.nvidia.com/cufft
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: cuFFT native runtime libraries
      description: |
        The cuFFT library provides GPU-accelerated Fast Fourier Transform (FFT) implementations.
      doc_url: https://docs.nvidia.com/cuda/cufft/
      dev_url: https://docs.nvidia.com/cuda/cufft/

  - name: libcufft-dev
    build:
      run_exports:
        weak:
          - {{ pin_subpackage("libcufft", max_pin="x") }}
      # Repacked binaries on linux aarch64 have flag DT_TLSDESC (GNU_HASH),
      # which is not supported by LIEF and can raise ValueError during
      # overlinking checks. Ignore all cuFFT shared objects for overlinking checks.
      overlinking_ignore_patterns:  # [linux and aarch64]
        - "targets/{{ target_name }}/lib/libcufft*.so*"         # [linux and aarch64]
        - "targets/{{ target_name }}/lib/libcufftw*.so*"        # [linux and aarch64]
        - "lib/libcufft*.so*"                                   # [linux and aarch64]
        - "lib/libcufftw*.so*"                                  # [linux and aarch64]
      # conda_build.exceptions.RunPathError: runpaths check failed
      # ERROR (libcufft-dev,targets/*/lib/stubs/libcufft.so): runpaths ['$ORIGIN'] found
      # The stub files use $ORIGIN runpaths which are valid but flagged by conda-build
      # This whitelist allows $ORIGIN runpaths in the stub files during build-time validation.
      # Note: We have comprehensive rpath validation in test-rpath.sh that ensures all libraries
      # have the correct $ORIGIN rpath for runtime compatibility.
      runpath_whitelist:  # [linux]
        - $ORIGIN  # [linux]
    files:
      - lib/libcufft*.so                                  # [linux]
      - lib/pkgconfig                                     # [linux]
      - targets/{{ target_name }}/include                 # [linux]
      - targets/{{ target_name }}/lib/libcufft*.so        # [linux]
      - targets/{{ target_name }}/lib/stubs/libcufft*.so  # [linux]
      - Library\include                                   # [win]
      - Library\lib\{{ target_name }}                     # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("libcufft", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - libcufft-static >={{ version }}  # [linux]
    test:
      commands:
        - test -L $PREFIX/lib/libcufft.so                                   # [linux]
        - test -L $PREFIX/lib/libcufftw.so                                  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cudalibxt.h     # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cufft.h         # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cufftw.h        # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cufftXt.h       # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufft.so         # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufftw.so        # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libcufft.so   # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libcufftw.so  # [linux]
        - if not exist %LIBRARY_INC%\cudalibxt.h exit 1                     # [win]
        - if not exist %LIBRARY_INC%\cufft.h exit 1                         # [win]
        - if not exist %LIBRARY_INC%\cufftw.h exit 1                        # [win]
        - if not exist %LIBRARY_INC%\cufftXt.h exit 1                       # [win]
        - if not exist %LIBRARY_LIB%\{{ target_name }}\cufft.lib exit 1     # [win]
        - if not exist %LIBRARY_LIB%\{{ target_name }}\cufftw.lib exit 1    # [win]
    about:
      home: https://developer.nvidia.com/cufft
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: cuFFT native runtime libraries
      description: |
        The cuFFT library provides GPU-accelerated Fast Fourier Transform (FFT) implementations.
      doc_url: https://docs.nvidia.com/cuda/cufft/
      dev_url: https://docs.nvidia.com/cuda/cufft/

  - name: libcufft-static
    # cuFFT does not ship `*_static.lib` on Windows so only relevant on linux
    build:
      skip: true  # [not linux]
    files:
      - targets/{{ target_name }}/lib/libcufft*_static*.a
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufft_static.a
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufftw_static.a
    about:
      home: https://developer.nvidia.com/cufft
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: cuFFT native runtime libraries
      description: |
        The cuFFT library provides GPU-accelerated Fast Fourier Transform (FFT) implementations.
      doc_url: https://docs.nvidia.com/cuda/cufft/
      dev_url: https://docs.nvidia.com/cuda/cufft/

about:
  home: https://developer.nvidia.com/cufft
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: cuFFT native runtime libraries
  description: |
    The cuFFT library provides GPU-accelerated Fast Fourier Transform (FFT) implementations.
  doc_url: https://docs.nvidia.com/cuda/cufft/
  dev_url: https://docs.nvidia.com/cuda/cufft/

extra:
  skip-lints:
    - license_file_overspecified
  recipe-maintainers:
    - conda-forge/cuda